### ISSUE TITLE
declareQueue does not accept dash character

### ISSUE THREAD

**Issue by beckend** [lenkan/deno-amqp#21]
https://github.com/lenkan/deno-amqp/blob/master/src/amqp_channel.ts#L238
```typescript
  async declareQueue(args: QueueDeclareArgs): Promise<QueueDeclareOk> {
    return this.#protocol.sendQueueDeclare(this.#channelNumber, args);
  }

// usage
  await channel.declareQueue({
    ....,
    arguments: {                
       'x-max-length': 1000000,                        
       'x-max-length-bytes': 1048576000,
    }
  })
```
`-` character has code 45.

**Comment by lenkan** [comment]
Hi,

This is because it is not listed as a valid character in the AMQP spec https://www.rabbitmq.com/protocol.html. See section 4.2.5.5 Field Tables.

It is explicitly verified in the encoder here: 

- https://github.com/lenkan/deno-amqp/blob/master/src/encoding/amqp_encoder.ts#L210
- https://github.com/lenkan/deno-amqp/blob/master/src/encoding/amqp_encoder.ts#L36

I briefly tested adding the dash character as valid character and the rabbitMQ server seems to accept it. PRs welcome. If possible, please refer to another client library where they allow `-` as a field name.
